sudo: required
services:
  - docker

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - docker pull nginx
  - docker pull python:3
  - docker pull jwilder/docker-gen

before_script:
  - echo 'DOCKER_OPTS+=" --debug=true" | sudo tee /etc/default/docker'
  - sudo restart docker

script:
  - docker build -t jwilder/nginx-proxy:bats .
  - bats test
